In [1]:
# 모듈 import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('/content/drive/MyDrive/KDThome/santander-customer-transaction-prediction/train.csv')
df.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [3]:
df_1 = df.drop('ID_code', axis=1, inplace=False)

In [5]:
# 전처리는 이상치만. 결측치는 없음
# 소수의 이상치는 중앙값으로
# target 제외한 컬럼만 추출
features = df_1.drop('target', axis=1)

# 이상치를 중앙값으로 대체
df_fixed = df_1.copy()

for col in features.columns:
    Q1 = df_1[col].quantile(0.25)
    Q3 = df_1[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # 이상치 탐지
    outlier_mask = (df_1[col] < lower_bound) | (df_1[col] > upper_bound)

    # 이상치 중앙값으로 대체
    median = df_1[col].median()
    df_fixed.loc[outlier_mask, col] = median

# 결과 확인
print("✅ 이상치 중앙값으로 대체 완료")
print(df_fixed.shape)

✅ 이상치 중앙값으로 대체 완료
(200000, 201)

In [7]:
# 데이터분리
x_data = df_fixed.drop('target', axis=1, inplace=False).values
t_data = df_fixed['target'].values

# 테스트 데이터 분리
x_data_train, x_data_test, t_data_train, t_data_test =\
train_test_split(x_data,
                 t_data,
                 test_size=0.2,
                 stratify=t_data)

In [6]:
df_fixed.head()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,-4.9200,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,3.1468,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,-4.9193,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,-5.8609,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,6.2654,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [8]:
# 정규화
scaler = StandardScaler()
x_data_train_norm = scaler.fit_transform(x_data_train)
x_data_test_norm = scaler.fit_transform(x_data_test)

In [9]:
# 오버샘플링
sm = SMOTE()
x_data_train_norm_sm, t_data_train_sm = sm.fit_resample(x_data_train_norm, t_data_train)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier

# 로지스틱 회귀 모델
logistic = LogisticRegression()

In [14]:
pip install optuna

Collecting optuna
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.40)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.13.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Downloading optuna-4.3.0-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.6/386.6 kB 9.8 MB/s eta 0:00:00
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 13.1 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.15.2 colorlog-6.9.0 optuna-4.3.0

In [15]:
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedKFold

In [16]:
# Optuna 최적화용 함수
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
        'random_state': 42,
        'use_label_encoder': False,
        'verbosity': 0,
        'n_jobs': -1
    }

    model = XGBClassifier(**params)

    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = cross_val_score(model, x_data_train_norm_sm, t_data_train_sm,
                             scoring='f1', cv=skf, n_jobs=-1)
    return scores.mean()

In [17]:
# 최적화 실행
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)

# 최적 파라미터 출력
print("Best Score:", study.best_value)
print("Best Params:", study.best_params)

[I 2025-04-18 08:08:41,592] A new study created in memory with name: no-name-abd16dfa-a680-410b-8648-1bec2b2be467
[I 2025-04-18 08:18:14,333] Trial 0 finished with value: 0.9443054830744595 and parameters: {'n_estimators': 436, 'max_depth': 10, 'learning_rate': 0.12900066274252145, 'subsample': 0.7766380612503516, 'colsample_bytree': 0.9325177961785522, 'gamma': 3.642410999980977, 'reg_alpha': 0.9377715474184656, 'reg_lambda': 0.612426567669206}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:19:41,054] Trial 1 finished with value: 0.792118502452547 and parameters: {'n_estimators': 178, 'max_depth': 3, 'learning_rate': 0.016045308599646528, 'subsample': 0.5386612177484387, 'colsample_bytree': 0.6198613331525775, 'gamma': 2.057203725408553, 'reg_alpha': 0.4677886931601777, 'reg_lambda': 0.47256347494232587}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:21:50,349] Trial 2 finished with value: 0.8696510523062851 and parameters: {'n_estimators': 119, 'max_depth': 7, 'learning_rate': 0.03308850852575362, 'subsample': 0.8261645474480106, 'colsample_bytree': 0.6952792671026371, 'gamma': 0.42683520401259556, 'reg_alpha': 0.7607266100022412, 'reg_lambda': 0.9710736120321029}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:23:17,426] Trial 3 finished with value: 0.8147321768096828 and parameters: {'n_estimators': 121, 'max_depth': 5, 'learning_rate': 0.01796783272133603, 'subsample': 0.9417012405406985, 'colsample_bytree': 0.6648760455581553, 'gamma': 2.676290203311119, 'reg_alpha': 0.3791583228862472, 'reg_lambda': 0.9711701383154837}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:26:27,797] Trial 4 finished with value: 0.9057093969018147 and parameters: {'n_estimators': 191, 'max_depth': 7, 'learning_rate': 0.07945208627043633, 'subsample': 0.5768825999983186, 'colsample_bytree': 0.738562905977786, 'gamma': 0.22765626773075587, 'reg_alpha': 0.0037025261102432427, 'reg_lambda': 0.592212034902291}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:29:35,009] Trial 5 finished with value: 0.8875255987031786 and parameters: {'n_estimators': 379, 'max_depth': 4, 'learning_rate': 0.0923642146848191, 'subsample': 0.7767022681959557, 'colsample_bytree': 0.9836954340745523, 'gamma': 0.4711493633358843, 'reg_alpha': 0.46495261036254387, 'reg_lambda': 0.41373268761342774}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:33:56,879] Trial 6 finished with value: 0.9148520503596634 and parameters: {'n_estimators': 487, 'max_depth': 5, 'learning_rate': 0.15142106342037814, 'subsample': 0.6353513760818408, 'colsample_bytree': 0.7787639630420328, 'gamma': 1.5982636159447923, 'reg_alpha': 0.695548820894009, 'reg_lambda': 0.21017512991161036}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:39:24,644] Trial 7 finished with value: 0.9382155121258696 and parameters: {'n_estimators': 301, 'max_depth': 8, 'learning_rate': 0.14160160305643651, 'subsample': 0.7047216609560951, 'colsample_bytree': 0.6511837138307682, 'gamma': 2.8631422082834423, 'reg_alpha': 0.8610964429407563, 'reg_lambda': 0.18640581922828636}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:44:23,388] Trial 8 finished with value: 0.936298948090828 and parameters: {'n_estimators': 357, 'max_depth': 7, 'learning_rate': 0.22563805401540846, 'subsample': 0.5055076277483842, 'colsample_bytree': 0.6804012347470725, 'gamma': 1.0723031711867548, 'reg_alpha': 0.9499953371355366, 'reg_lambda': 0.09737078580073955}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:45:52,758] Trial 9 finished with value: 0.8774000319541555 and parameters: {'n_estimators': 153, 'max_depth': 4, 'learning_rate': 0.2213159023762597, 'subsample': 0.6534263578712707, 'colsample_bytree': 0.6172350225029004, 'gamma': 3.648302406892941, 'reg_alpha': 0.6798076585166934, 'reg_lambda': 0.8502446628438768}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:51:32,687] Trial 10 finished with value: 0.9363349641745605 and parameters: {'n_estimators': 499, 'max_depth': 10, 'learning_rate': 0.2898157578440482, 'subsample': 0.8978328757817962, 'colsample_bytree': 0.9728654227773469, 'gamma': 4.687585515494625, 'reg_alpha': 0.21548661083123233, 'reg_lambda': 0.7053145338392903}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 08:57:33,559] Trial 11 finished with value: 0.9411094814586446 and parameters: {'n_estimators': 285, 'max_depth': 10, 'learning_rate': 0.15091212474467197, 'subsample': 0.7039866995777233, 'colsample_bytree': 0.515774318132816, 'gamma': 3.185241958868846, 'reg_alpha': 0.9798701255830016, 'reg_lambda': 0.31168507690586933}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 09:03:28,385] Trial 12 finished with value: 0.9385979629242529 and parameters: {'n_estimators': 405, 'max_depth': 10, 'learning_rate': 0.19541087559244902, 'subsample': 0.7983639894934067, 'colsample_bytree': 0.5044421160074333, 'gamma': 3.824015231316231, 'reg_alpha': 0.9966602961545825, 'reg_lambda': 0.34412716964912277}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 09:10:11,804] Trial 13 finished with value: 0.9389057770072845 and parameters: {'n_estimators': 249, 'max_depth': 9, 'learning_rate': 0.11142539468277418, 'subsample': 0.7304074694288821, 'colsample_bytree': 0.8654577648368224, 'gamma': 3.530171476483802, 'reg_alpha': 0.825726519920037, 'reg_lambda': 0.651061939209185}. Best is trial 0 with value: 0.9443054830744595.
[I 2025-04-18 09:16:12,828] Trial 14 finished with value: 0.9405386964241167 and parameters: {'n_estimators': 293, 'max_depth': 9, 'learning_rate': 0.17731567407043877, 'subsample': 0.8543610218045639, 'colsample_bytree': 0.8703939095142499, 'gamma': 4.214241747854766, 'reg_alpha': 0.6365021897440061, 'reg_lambda': 0.30657542985462216}. Best is trial 0 with value: 0.9443054830744595.
[W 2025-04-18 09:19:47,227] Trial 15 failed with parameters: {'n_estimators': 421, 'max_depth': 9, 'learning_rate': 0.1367714555057539, 'subsample': 0.6378634180266461, 'colsample_bytree': 0.506600497796641, 'gamma': 3.102986835688189, 'reg_alpha': 0.9046809828589468, 'reg_lambda': 0.5439513264736933} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "<ipython-input-16-a42409c1cf99>", line 21, in objective
    scores = cross_val_score(model, x_data_train_norm_sm, t_data_train_sm,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/usr/local/lib/python3.11/dist-packages/joblib/parallel.py", line 1762, in _retrieve
    time.sleep(0.01)
KeyboardInterrupt
[W 2025-04-18 09:19:47,234] Trial 15 failed with value None.

KeyboardInterrupt:

In [ ]:
best_params = study.best_params
best_params.update({
    'use_label_encoder': False,
    'verbosity': 0,
    'n_jobs': -1
})

xgb_best = XGBClassifier(**best_params)
xgb_best.fit(x_data_train_norm_sm, t_data_train_sm)

In [ ]:
# 로지스틱 회귀 모델 정의
logistic = LogisticRegression(max_iter=1000, random_state=42)

# 최적 XGBoost 모델 정의
best_params.update({
    'use_label_encoder': False,
    'verbosity': 0,
    'n_jobs': -1
})
xgb_best = XGBClassifier(**best_params)

# 앙상블 모델 (soft voting 사용)
ensemble_model = VotingClassifier(
    estimators=[
        ('xgb', xgb_best),
        ('logistic', logistic)
    ],
    voting='soft',  # 확률 평균 기반
    n_jobs=-1
)

In [ ]:
# 학습
ensemble_model.fit(x_data_train_norm_sm, t_data_train_sm)