In [22]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/KDTHome/[data]/auto-mpg.csv',
                 header=None)

df.columns=['mpg', 'cylinders', 'displacement', 'horsepower',
            'weight', 'acceleration', 'model_year', 'origin', 'name']

# display(df)

# 1. head() : DataFrame의 상위 5개의 row를 가져와서 DataFrame으로 생성
#             인자로 숫자를 사용할 수 있어요!
# 2. tail() : DataFrame의 하위 5개의 row를 가져와서 DataFrame으로 생성
#             인자로 숫자를 사용할 수 있어요!
# display(df.head())
# display(df.tail())

# 3. shape
# print(df.shape)  # (398, 9)
# 4. info() : DataFrame의 기본 정보를 화면에 출력할 수 있어요!
#             print()를 사용하지 않고 함수 자체로 출력기능을 가지고 있어요!
# df.info()

# 4. count()
#    DataFrame이 가지고 있는 각 열의 데이터의 개수를 Seires로 리턴
#    count()는 유효한 값만 counting해요! NaN은 counting하지 않아요!~
# print(df.count())

# 5. value_counts() : Series가 가지고 있는 함수예요!
#                     unique value가 몇개 있는지 알려줘요!
#                     NaN을 포함할건지 제외할건지를 옵션으로 명시
#                     dropna=True
# print(df['origin'].value_counts())

# 6. unique() : Series가 가지고 있는 함수!
#               중복을 제거하는 함수
# print(df['model_year'].unique())
# [70 71 72 73 74 75 76 77 78 79 80 81 82]

# 7. isin() : 어떤값이 내가 정한 값들 안에 들어 있으면 True
#             boolean indexing할 때 많이 사용!
# print(df['origin'].isin([1,2]))

# 제조국이 미국, EU가 아닌 차량의 mpg와 origin, name을 조회하세요!
# df.loc[~df['origin'].isin([1,2]), ['mpg', 'origin', 'name']]

      mpg  origin                   name
14   24.0       3  toyota corona mark ii
18   27.0       3           datsun pl510
29   27.0       3           datsun pl510
31   25.0       3          toyota corona
53   31.0       3    toyota corolla 1200
..    ...     ...                    ...
382  34.0       3         toyota corolla
383  38.0       3            honda civic
384  32.0       3     honda civic (auto)
385  38.0       3          datsun 310 gx
390  32.0       3       toyota celica gt

[79 rows x 3 columns]

In [39]:
# 8. sort() : 정렬하는 함수
import numpy as np
import pandas as pd

np.random.seed(1)  # 난수의 재현을 위해서 seed 설정
arr = np.random.randint(0,10,(6,4))
# print(arr)
df = pd.DataFrame(arr)
df.columns = ['A', 'B', 'C', 'D']
df.index = pd.date_range('20250101', periods=6)
# display(df)

# 적절하게 DataFrame을 섞어볼거예요!
# 값을 섞을때 사용하는 함수는 대표적으로 shuffle()
# index는 mutable operation을 지원하지 않아요!
# shuffle은 mutable operation을 하는 함수예요!
# 고로 shuffle은 index를 섞는데 사용할 수 없어요!
random_date = np.random.permutation(df.index)
# print(random_date)
# df.index = random_date # 이렇게 하면 안되요!!
new_df = df.reindex(index=random_date,
                    columns=['B', 'A', 'D', 'C'])
display(new_df)

# 이제 정렬을 해 보아요!
# index를 이용한 정렬과 value(값)을 이용한 정렬이 있어요!

# index를 이용한 정렬부터 알아보아요! 당연히 정렬할때
# axis를 설정
# display(new_df.sort_index(axis=0, ascending=False))

# value를 이용한 정렬
display(new_df.sort_values(by='B'))

            B  A  D  C
2025-01-03  9  6  4  2
2025-01-01  8  5  5  9
2025-01-04  2  5  2  4
2025-01-05  7  4  9  7
2025-01-02  0  0  7  1
2025-01-06  7  1  6  0

            B  A  D  C
2025-01-02  0  0  7  1
2025-01-04  2  5  2  4
2025-01-06  7  1  6  0
2025-01-05  7  4  9  7
2025-01-01  8  5  5  9
2025-01-03  9  6  4  2

In [52]:
# DataFrame의 기술통계(Descriptive Statistics)를 위한 함수들이 있어요!
# sum(), mean(), max(), min(), count(), std(), ...
# Numpy때는 axis를 사용하지 않으면 => 전체 naddray를 대상으로 함수를 적용
# Pandas는 axis를 사용하지 않으면 => 기본 axis=0 (행방향)를 기준.

import numpy as np
import pandas as pd

data = np.array([[2, np.nan],
                 [7, -3],
                 [np.nan, np.nan],
                 [1, -2]])
# print(data)
df = pd.DataFrame(data,
                  columns=['one', 'two'],
                  index=['a', 'b', 'c', 'd'])
display(df)

# print(df.sum())  # df.sum(axis=0,
#                         skipna=True)
#                  Series로 리턴

# 특정 열에 대한 합
# print(df['two'].sum())  # -5
# 특정 행에 대한 합
# print(df.loc['b'].sum()) # 4.0

# 평균을 구할때는 mean()
# print(df.mean())



result = df['one'].fillna(value=df['one'].mean())
df['one'] = result
display(df)

   one  two
a  2.0  NaN
b  7.0 -3.0
c  NaN  NaN
d  1.0 -2.0

        one  two
a  2.000000  NaN
b  7.000000 -3.0
c  3.333333  NaN
d  1.000000 -2.0

In [75]:
# 데이터 처리를 위한 함수들을 알아보기  위해
# 데이터셋을 사용할꺼예요!
# MPG Data Set(자동차 연비)과 Titanic Data Set을 사용할 꺼예요!

# Titanic Data Set은 워낙 유명한 Data set으로
# 다양한 경로로 데이터를 구해서 사용할 수 있어요!
# 그 중 우리는 seaborn library에서 제공하는 데이터셋을 사용할꺼예요!

# 1. 결치값 확인!

import numpy as np
import pandas as pd
import seaborn as sns

# raw data set을 가져와요!
df = sns.load_dataset('titanic')

# display(df.head())
# print(df.shape) # (891, 15)

# df.info()

# deck 컬럼의 결측치 개수를 알고 싶어요! => 많이 쓰는 방법은 아니예요!
# print(df['deck'].value_counts(dropna=False))

# 결측치를 직접 찾는 방법으로 가장 많이 사용하는 함수가 있어요!
# isnull()
# display(df.head())
# display(df.isnull().sum(axis=0))
# display(df.notnull())

# 2. 결치값 삭제(컬럼단위로 삭제와 행 단위로 삭제)

# 결측치 확인 끝나면 특정 조건을 이용해서 결측치가 포함된 column을 삭제
# 할 수 있어요!
new_df = df.dropna(axis=1, inplace=False, thresh=500)
# display(new_df)
display(new_df.isnull().sum(axis=0))

# 가장 문제가 되는 컬럼을 삭제처리!
# NaN을 포함하는 행을 찾아서 삭제하거나 대체해야 해요!
# df2 = new_df.dropna(axis=0, how='any')
df2 = new_df.dropna(subset=['age'], axis=0, how='any')
display(df2.isnull().sum(axis=0))

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [95]:
import numpy as np
import pandas as pd
import seaborn as sns

# raw data set을 가져와요!
df = sns.load_dataset('titanic')

# 일단 deck 컬럼은 삭제하도록 해요!
new_df = df.dropna(axis=1,
                  inplace=False,
                  thresh=500)

# print(new_df.isnull().sum())
# display(new_df)

# embark_town에 2개의 값이 결측치예요!
# 1. embark_town의 값들 중 가장 빈도수가 많은 값을 찾아서
#    NaN 대용으로 사용해볼꺼예요!
# 참고
# s = pd.Series([5,2,8,6,3])
# 이 중 가장 큰 값의 index를 찾아보아요!
# print(s.max()) # 8
# print(s.idxmax()) # 2

new_df['embark_town'].fillna(new_df['embark_town'].value_counts().idxmax(),
                             inplace=True)

print(new_df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

<ipython-input-95-39570fb397bc>:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['embark_town'].fillna(new_df['embark_town'].value_counts().idxmax(),
<ipython-input-95-39570fb397bc>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['embark_town'].fillna(new_df['embark_town'].value_counts().idxmax(),